####
# Runtime-only Dockerfile:
# - Expects the native binary already generated by Maven in target/*-runner
# - Produces a smaller runtime image using Quarkus micro image
#
# Build:
# docker build -f Dockerfile -t demo-crud:native-runtime .
#
# Run:
# docker run -i --rm -p 8080:8080 demo-crud:native-runtime
###
ARG RUNTIME_IMAGE=registry-ctn.prevnet/quarkus/ubi9-quarkus-micro-image:2.0

FROM ${RUNTIME_IMAGE}
WORKDIR /work/
RUN chown 1001 /work && chmod "g+rwX" /work && chown 1001:root /work
COPY --chown=1001:root --chmod=0755 target/*-runner /work/application
EXPOSE 8080
USER 1001
ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
