apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}  
data:
{{- if .Values.postgres.enabled }}
  QUARKUS_DATASOURCE_USERNAME: {{ .Values.postgres.auth.username | quote }}
  QUARKUS_DATASOURCE_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  QUARKUS_DATASOURCE_JDBC_URL: {{ printf "jdbc:postgresql://%s:5432/%s" .Values.postgres.serviceName .Values.postgres.auth.database | quote }}
{{- end }}
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | toString | quote }}
{{- end }}
